language: node_js

node_js:
  - 4.2.6

install:
  - npm install

services: 
  - mongodb

script:
#  - ./test/install.sh && npm run cover
  - npm run cover

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

#notifications:
#  slack: research-technologies:izdZdry8NEjrDmTjbHL5dCA8


